/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de302;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class ruongfr extends javax.swing.JFrame {

    /**
     * Creates new form ruongfr
     */
    public ruongfr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmaruong = new javax.swing.JTextField();
        txttenchuho = new javax.swing.JTextField();
        txtloaicay = new javax.swing.JTextField();
        txtcanh = new javax.swing.JTextField();
        txtdai = new javax.swing.JTextField();
        txtrong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        loairuong = new javax.swing.JComboBox<>();
        btnluu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtthongke = new javax.swing.JTextArea();
        btnluufile = new javax.swing.JButton();
        btnthongke = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Điền thông tin ");

        jLabel2.setText("Mã ruộng");

        jLabel3.setText("Tên chủ hộ");

        jLabel4.setText("Loại cây trồng");

        jLabel5.setText("Cạnh");

        jLabel6.setText("Chiều dài");

        jLabel7.setText("Chiều rộng");

        txtmaruong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaruongActionPerformed(evt);
            }
        });

        txttenchuho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenchuhoActionPerformed(evt);
            }
        });

        txtloaicay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloaicayActionPerformed(evt);
            }
        });

        txtcanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcanhActionPerformed(evt);
            }
        });

        txtdai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaiActionPerformed(evt);
            }
        });

        txtrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrongActionPerformed(evt);
            }
        });

        jLabel8.setText("Loại ruộng");

        loairuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vuông", "Chữ nhật" }));
        loairuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loairuongActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thống kê");

        txtthongke.setColumns(20);
        txtthongke.setRows(5);
        jScrollPane1.setViewportView(txtthongke);

        btnluufile.setText("Lưu File");
        btnluufile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluufileActionPerformed(evt);
            }
        });

        btnthongke.setText("Thống kê");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loairuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdai, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(txtmaruong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcanh, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtloaicay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnluu)
                .addGap(200, 200, 200)
                .addComponent(btnluufile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnthongke)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmaruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtloaicay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(loairuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu)
                    .addComponent(btnluufile)
                    .addComponent(btnthongke))
                .addGap(0, 285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaruongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaruongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaruongActionPerformed

    private void txttenchuhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenchuhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenchuhoActionPerformed

    private void txtloaicayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloaicayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloaicayActionPerformed

    private void txtcanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcanhActionPerformed

    private void txtdaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaiActionPerformed

    private void txtrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrongActionPerformed

    private void loairuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loairuongActionPerformed
        
    }//GEN-LAST:event_loairuongActionPerformed

    ArrayList<Ruong> ds = new ArrayList<>();
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        
        String c = (String) loairuong.getSelectedItem();
        if (c.equals("Vuông")) {
            RuongVuong rv = new RuongVuong();
            rv.maRuong = txtmaruong.getText();
            rv.tenChuHo = txttenchuho.getText();
            rv.loaiCayTrong = txtloaicay.getText();
            rv.canh = Integer.parseInt(txtcanh.getText());
            ds.add(rv);
        }
        else {
            RuongChuNhat rcn = new RuongChuNhat();
            rcn.maRuong = txtmaruong.getText();
            rcn.tenChuHo = txttenchuho.getText();
            rcn.loaiCayTrong = txtloaicay.getText();
            rcn.chieuDai = Integer.parseInt(txtdai.getText());
            rcn.chieuRong = Integer.parseInt(txtrong.getText());
            ds.add(rcn);
        }
        txtmaruong.setText("");
        txttenchuho.setText("");
        txtloaicay.setText("");
        txtcanh.setText("");
        txtdai.setText("");
        txtrong.setText("");
        
    }//GEN-LAST:event_btnluuActionPerformed
    
    private void btnluufileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluufileActionPerformed
        File f = new File("ruong.txt");
        try {
            PrintWriter pw = new PrintWriter(f);
            String c = (String) loairuong.getSelectedItem();
            if (c=="Vuông") {
                RuongVuong rv = new RuongVuong();
                rv.maRuong = txtmaruong.getText();
                rv.tenChuHo = txttenchuho.getText();
                rv.loaiCayTrong = txtloaicay.getText();
                rv.canh = Integer.parseInt(txtcanh.getText());
                ds.add(rv);
            }
            else {
                RuongChuNhat rcn = new RuongChuNhat();
                rcn.maRuong = txtmaruong.getText();
                rcn.tenChuHo = txttenchuho.getText();
                rcn.loaiCayTrong = txtloaicay.getText();
                rcn.chieuDai = Integer.parseInt(txtdai.getText());
                rcn.chieuRong = Integer.parseInt(txtrong.getText());
                ds.add(rcn);
            }
            for (Object d : ds) {
                pw.println(d);
            }
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ruongfr.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnluufileActionPerformed

    int sv=0;
    int scn=0;
    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        for (Ruong d : ds) {
            if(d instanceof RuongVuong) sv ++;
            else scn++;
        }
        txtthongke.setText("");
        txtthongke.append("So ruong vuong: "+sv+"\n");
        txtthongke.append("So ruong chu nhat: "+scn);
    }//GEN-LAST:event_btnthongkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruongfr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnluufile;
    private javax.swing.JButton btnthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> loairuong;
    private javax.swing.JTextField txtcanh;
    private javax.swing.JTextField txtdai;
    private javax.swing.JTextField txtloaicay;
    private javax.swing.JTextField txtmaruong;
    private javax.swing.JTextField txtrong;
    private javax.swing.JTextField txttenchuho;
    private javax.swing.JTextArea txtthongke;
    // End of variables declaration//GEN-END:variables
}
