/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de202;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nhapma = new javax.swing.JTextField();
        btnfind = new javax.swing.JButton();
        btnsx = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtds = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập mã hàng:");

        nhapma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapmaActionPerformed(evt);
            }
        });

        btnfind.setText("Tìm");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnsx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsx.setText("Sắp xếp");
        btnsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsxActionPerformed(evt);
            }
        });

        txtds.setColumns(20);
        txtds.setRows(5);
        jScrollPane1.setViewportView(txtds);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(nhapma, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnfind)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsx, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsx, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhapmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapmaActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        String f = nhapma.getText();
        Scanner sc = null;
        try {
            sc = new Scanner(new File("mathang.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<MatHang> dshang = new ArrayList<>();
        while(sc.hasNextLine()) {
            String line = sc.nextLine();
            String[] h = line.split(";");
            if(h[0].equalsIgnoreCase("A"))
                dshang.add(new MonAn(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
            else 
                dshang.add(new DoUong(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
        }
        sc.close();
        for (MatHang h:dshang) {
            if(h.maHang.equalsIgnoreCase(f))
                h.hienThi();
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsxActionPerformed
        Scanner sc = null;
        try {
            sc = new Scanner(new File("mathang.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<MatHang> dshang = new ArrayList<>();
        while(sc.hasNextLine()) {
            String line = sc.nextLine();
            String[] h = line.split(";");
            if(h[0].equalsIgnoreCase("A"))
                dshang.add(new MonAn(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
            else 
                dshang.add(new DoUong(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
        }
        sc.close();
        dshang.sort((a,b)->Float.compare(b.getGia(), a.getGia()));
        txtds.setText("");
        for (MatHang h : dshang) {
            txtds.append(h.toString()+"\n");
        }
    }//GEN-LAST:event_btnsxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        Scanner sc= new Scanner(new File("mathang.txt"));
        ArrayList<MatHang> dshang = new ArrayList<>();
        while(sc.hasNextLine()) {
            String line = sc.nextLine();
            String[] h = line.split(";");
            if(h[0].equalsIgnoreCase("A"))
                dshang.add(new MonAn(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
            else 
                dshang.add(new DoUong(true, h[1], h[2], Integer.parseInt(h[3]), Integer.parseInt(h[4]), Float.parseFloat(h[5])));
        }
        sc.close();
        for (MatHang h : dshang) {
            h.hienThi();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnsx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nhapma;
    private javax.swing.JTextArea txtds;
    // End of variables declaration//GEN-END:variables
}
